import { ChargingStation } from "@/types/station";

export type { ChargingStation };

export const STATIONS: ChargingStation[] = [
  // --- SURFACE & OUTDOOR DEDICATED HUBS (DENZA D9 & LARGE EV APPROVED) ---
  {
    id: "spklu-danareksa",
    name: "SPKLU Menara Danareksa (Outdoor Plaza)",
    lat: -6.1834,
    lng: 106.8248,
    power: "200 kW Ultra Fast",
    kw: 200,
    brand: "PLN",
    connectors: ["CCS2"],
    parking_type: "Surface",
    height_clearance_m: 99,
    bay_length_m: 5.8,
    denza_approved: true,
    open_data: true,
    address: "Jl. Medan Merdeka Selatan No.14, Gambir",
    operating_hours: "24 Hours",
    fee_per_kwh: 2466,
  },
  {
    id: "spklu-uid-gambir",
    name: "SPKLU PLN UID Jakarta Raya (Main Yard)",
    lat: -6.1751,
    lng: 106.8271,
    power: "150 kW Ultra Fast",
    kw: 150,
    brand: "PLN",
    connectors: ["CCS2", "CHAdeMO"],
    parking_type: "Dedicated Hub",
    height_clearance_m: 99,
    bay_length_m: 6.2,
    denza_approved: true,
    open_data: true,
    address: "Jl. M.I. Ridwan Rais No.1, Gambir",
    operating_hours: "24 Hours",
    fee_per_kwh: 2466,
  },
  {
    id: "spklu-pln-pusat",
    name: "SPKLU Kantor Pusat PLN (Courtyard)",
    lat: -6.2372,
    lng: 106.8014,
    power: "100 kW Fast",
    kw: 100,
    brand: "PLN",
    connectors: ["CCS2", "Type 2"],
    parking_type: "Surface",
    height_clearance_m: 99,
    bay_length_m: 5.6,
    denza_approved: true,
    open_data: true,
    address: "Jl. Trunojoyo Blok M-I No.135, Kebayoran Baru",
    operating_hours: "24 Hours",
    fee_per_kwh: 2466,
  },
  {
    id: "spklu-senayan-gbk",
    name: "SPKLU GBK Senayan (Parkir Timur)",
    lat: -6.2185,
    lng: 106.8052,
    power: "100 kW Fast",
    kw: 100,
    brand: "PLN",
    connectors: ["CCS2", "Type 2"],
    parking_type: "Surface",
    height_clearance_m: 99,
    bay_length_m: 6.0,
    denza_approved: true,
    open_data: true,
    address: "Gelora Bung Karno Parkir Timur, Senayan",
    operating_hours: "06:00 - 22:00",
    fee_per_kwh: 2466,
  },
  {
    id: "shell-fatmawati",
    name: "Shell Recharge Fatmawati (Forecourt)",
    lat: -6.2734,
    lng: 106.7967,
    power: "50 kW Fast",
    kw: 50,
    brand: "Shell",
    connectors: ["CCS2"],
    parking_type: "Curbside",
    height_clearance_m: 4.2,
    bay_length_m: 5.5,
    denza_approved: true,
    open_data: true,
    address: "Jl. RS. Fatmawati Raya No.23, Cilandak",
    operating_hours: "24 Hours",
    fee_per_kwh: 2466,
  },
  {
    id: "shell-antasari",
    name: "Shell Recharge Antasari 1 (Forecourt)",
    lat: -6.2624,
    lng: 106.8065,
    power: "50 kW Fast",
    kw: 50,
    brand: "Shell",
    connectors: ["CCS2"],
    parking_type: "Curbside",
    height_clearance_m: 4.2,
    bay_length_m: 5.4,
    denza_approved: true,
    open_data: true,
    address: "Jl. Pangeran Antasari No.18, Cilandak",
    operating_hours: "24 Hours",
    fee_per_kwh: 2466,
  },
  {
    id: "shell-sparman",
    name: "Shell Recharge S. Parman (Outdoor)",
    lat: -6.1852,
    lng: 106.7915,
    power: "50 kW Fast",
    kw: 50,
    brand: "Shell",
    connectors: ["CCS2"],
    parking_type: "Curbside",
    height_clearance_m: 4.0,
    bay_length_m: 5.5,
    denza_approved: true,
    open_data: true,
    address: "Jl. Letjen S. Parman Kav. 7, Slipi",
    operating_hours: "24 Hours",
    fee_per_kwh: 2466,
  },
  {
    id: "spklu-pln-bandengan",
    name: "SPKLU PLN UP3 Bandengan (Outdoor Bay)",
    lat: -6.1364,
    lng: 106.8021,
    power: "50 kW Fast",
    kw: 50,
    brand: "PLN",
    connectors: ["CCS2", "CHAdeMO"],
    parking_type: "Surface",
    height_clearance_m: 99,
    bay_length_m: 5.7,
    denza_approved: true,
    open_data: true,
    address: "Jl. Bandengan Utara Raya No.83, Penjaringan",
    operating_hours: "24 Hours",
    fee_per_kwh: 2466,
  },
  {
    id: "spklu-rest-km10",
    name: "SPKLU Jagorawi KM 10 (Rest Area Open Hub)",
    lat: -6.3458,
    lng: 106.8835,
    power: "200 kW Ultra Fast",
    kw: 200,
    brand: "PLN",
    connectors: ["CCS2"],
    parking_type: "Dedicated Hub",
    height_clearance_m: 99,
    bay_length_m: 6.5,
    denza_approved: true,
    open_data: true,
    address: "Tol Jagorawi KM 10 Arah Bogor",
    operating_hours: "24 Hours",
    fee_per_kwh: 2466,
  },
  {
    id: "spklu-rest-km19",
    name: "SPKLU Jakarta-Cikampek KM 19 (Outdoor Plaza)",
    lat: -6.2625,
    lng: 107.0392,
    power: "200 kW Ultra Fast",
    kw: 200,
    brand: "PLN",
    connectors: ["CCS2"],
    parking_type: "Dedicated Hub",
    height_clearance_m: 99,
    bay_length_m: 6.5,
    denza_approved: true,
    open_data: true,
    address: "Tol Jakarta-Cikampek Rest Area KM 19 Arah Timur",
    operating_hours: "24 Hours",
    fee_per_kwh: 2466,
  },
  {
    id: "spklu-ancol",
    name: "SPKLU Taman Impian Jaya Ancol (Pintu Timur)",
    lat: -6.1245,
    lng: 106.8323,
    power: "50 kW Fast",
    kw: 50,
    brand: "PLN",
    connectors: ["CCS2", "Type 2"],
    parking_type: "Surface",
    height_clearance_m: 99,
    bay_length_m: 5.6,
    denza_approved: true,
    open_data: true,
    address: "Kawasan Parkir Timur Ancol, Pademangan",
    operating_hours: "06:00 - 22:00",
    fee_per_kwh: 2466,
  },
  {
    id: "spklu-pik-avenue-outdoor",
    name: "SPKLU PIK Avenue (North Surface Lot)",
    lat: -6.1114,
    lng: 106.7389,
    power: "50 kW Fast",
    kw: 50,
    brand: "Starvo",
    connectors: ["CCS2"],
    parking_type: "Surface",
    height_clearance_m: 99,
    bay_length_m: 5.5,
    denza_approved: true,
    open_data: true,
    address: "Pantai Indah Kapuk Boulevard, Jakarta Utara",
    operating_hours: "10:00 - 22:00",
    fee_per_kwh: 2466,
  },
  {
    id: "spklu-pln-kebonjeruk",
    name: "SPKLU PLN UP3 Kebon Jeruk (Depot)",
    lat: -6.1924,
    lng: 106.7672,
    power: "50 kW Fast",
    kw: 50,
    brand: "PLN",
    connectors: ["CCS2"],
    parking_type: "Surface",
    height_clearance_m: 99,
    bay_length_m: 5.8,
    denza_approved: true,
    open_data: true,
    address: "Jl. Lapangan Bola No.1, Kebon Jeruk",
    operating_hours: "24 Hours",
    fee_per_kwh: 2466,
  },

  // --- BASEMENT & MALL HUBS (CAUTION: TIGHT BAY / LOW CEILING FOR DENZA D9) ---
  {
    id: "mall-senayan-city",
    name: "Senayan City (Basement B1)",
    lat: -6.2272,
    lng: 106.7972,
    power: "50 kW Fast",
    kw: 50,
    brand: "Voltron",
    connectors: ["CCS2"],
    parking_type: "Basement",
    height_clearance_m: 2.1,
    bay_length_m: 4.9,
    denza_approved: false, // Low clearance and tight bay
    open_data: true,
    address: "Jl. Asia Afrika Lot 19, Gelora",
    operating_hours: "10:00 - 22:00",
    fee_per_kwh: 2466,
  },
  {
    id: "mall-plaza-indonesia",
    name: "Plaza Indonesia (Basement P2)",
    lat: -6.1919,
    lng: 106.8229,
    power: "22 kW Medium",
    kw: 22,
    brand: "Starvo",
    connectors: ["Type 2"],
    parking_type: "Basement",
    height_clearance_m: 2.0,
    bay_length_m: 4.8,
    denza_approved: false,
    open_data: true,
    address: "Jl. M.H. Thamrin No.28-30, Gondangdia",
    operating_hours: "10:00 - 22:00",
    fee_per_kwh: 2466,
  },
  {
    id: "mall-pacific-place",
    name: "Pacific Place (Basement B2)",
    lat: -6.2246,
    lng: 106.8097,
    power: "22 kW Medium",
    kw: 22,
    brand: "PLN",
    connectors: ["Type 2"],
    parking_type: "Basement",
    height_clearance_m: 2.0,
    bay_length_m: 4.9,
    denza_approved: false,
    open_data: true,
    address: "SCBD Jl. Jend. Sudirman Kav. 52-53",
    operating_hours: "10:00 - 22:00",
    fee_per_kwh: 2466,
  },
  {
    id: "mall-central-park",
    name: "Central Park Mall (Basement B1)",
    lat: -6.1774,
    lng: 106.7919,
    power: "50 kW Fast",
    kw: 50,
    brand: "Starvo",
    connectors: ["CCS2"],
    parking_type: "Basement",
    height_clearance_m: 2.05,
    bay_length_m: 5.0,
    denza_approved: false,
    open_data: true,
    address: "Jl. Letjen S. Parman Kav. 28, Tanjung Duren",
    operating_hours: "10:00 - 22:00",
    fee_per_kwh: 2466,
  },
  {
    id: "mall-gandaria-city",
    name: "Gandaria City (Basement P1)",
    lat: -6.2443,
    lng: 106.7836,
    power: "50 kW Fast",
    kw: 50,
    brand: "Starvo",
    connectors: ["CCS2", "Type 2"],
    parking_type: "Basement",
    height_clearance_m: 2.1,
    bay_length_m: 4.9,
    denza_approved: false,
    open_data: true,
    address: "Jl. Sultan Iskandar Muda, Kebayoran Lama",
    operating_hours: "10:00 - 22:00",
    fee_per_kwh: 2466,
  },
  {
    id: "mall-kelapa-gading",
    name: "Mall Kelapa Gading 3 (Basement)",
    lat: -6.1585,
    lng: 106.9089,
    power: "22 kW Medium",
    kw: 22,
    brand: "PLN",
    connectors: ["Type 2"],
    parking_type: "Basement",
    height_clearance_m: 2.0,
    bay_length_m: 4.8,
    denza_approved: false,
    open_data: true,
    address: "Jl. Boulevard Raya, Kelapa Gading",
    operating_hours: "10:00 - 22:00",
    fee_per_kwh: 2466,
  },
];
